version: '3.1'
volumes:
  data:
services:
  db:
    image: postgres:14.3
    restart: always
    volumes:
      # Volume dos dados
      - data:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d postgres -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: email_sender
  frontend:
    image: nginx:alpine3.18
    volumes:
      - ./web:/usr/share/nginx/html/
    ports:
      - 80:80
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080