// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"context"
)

type Querier interface {
	CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error)
	DeleteEmail(ctx context.Context, id int32) error
	GetEmail(ctx context.Context, id int32) (Email, error)
	Listemails(ctx context.Context) ([]Email, error)
	UpdateEmail(ctx context.Context, arg UpdateEmailParams) (Email, error)
}

var _ Querier = (*Queries)(nil)
